SELECT * FROM [dbo].[house_pricing_dataset]

SELECT MIN (PRICE) FROM [dbo].[house_pricing_dataset]
WHERE PRICE >  0;

SELECT MAX (PRICE) FROM [dbo].[house_pricing_dataset]
WHERE PRICE > 0;

SELECT PRICE, CITY,
CASE 
      WHEN PRICE >= 7800 PRICE AND <= 500000 THEN 'AFORDABLE'
      WHEN PRICE > 500000 PRICE AND <= 5000000 THEN 'EXECUTIVE'
	  WHEN PRICE > 5000000 THEN 'LUXURY'
	  ELSE 'T_PAINERS'
END AS LIFESTYLE_STATUS
FROM [dbo].[house_pricing_dataset];